@startuml

class Bootstrap
class ServerBootstrap

abstract AbstractBootstrap
interface Cloneable


Cloneable <|.. AbstractBootstrap
AbstractBootstrap <|-- Bootstrap
AbstractBootstrap <|-- ServerBootstrap



interface EventLoopGroup

interface ChannelFactory

interface ChannelHandler


class BootstrapConfig


Bootstrap --> EventLoopGroup
Bootstrap --> ChannelFactory
Bootstrap --> ChannelHandler
Bootstrap --> BootstrapConfig

@enduml